on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notifications
    steps:
    - name: IRC notification
      uses: Gottox/irc-message-action@v2
      with:
        channel: '#zeppe-lin'
        nickname: zeppe-lin-bot
        message: |-
          ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
          ${{ join(github.event.commits.*.message, ', ') }}
          https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
